# Generated by Django 4.2.5 on 2023-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='resolved',
            field=models.CharField(choices=[('resolved', 'решено'), ('not resolved', 'не решено')], default='none', max_length=20),
        ),
    ]
